FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY backend/TheGadgetHub.API.csproj ./backend/
RUN dotnet restore ./backend/TheGadgetHub.API.csproj
COPY backend/ ./backend/
RUN dotnet publish ./backend/TheGadgetHub.API.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 80
ENTRYPOINT ["dotnet", "TheGadgetHub.API.dll"]
